<?php

declare(strict_types=1);

namespace AlfaCode\LetMigrate;

use AlfaCode\LetMigrate\Schema\Inspector\ColumnMeta;

/**
 * Computes the structural delta between two schema snapshots (FROM → TO)
 * and renders it as a single "update" migration.
 *
 * This is the ORM-free analogue of Doctrine's Comparator + SchemaDiff.
 * Pure logic over SchemaSnapshot arrays — no DB, no filesystem — so it is
 * fully unit-testable; the command supplies the two snapshots (typically
 * FROM = live DB, TO = a freshly-migrated reference / target).
 *
 * SAVE-DIFF MODE ($allowDestructive = false, the default):
 *   destructive operations (DROP TABLE / DROP COLUMN) are NOT emitted —
 *   this directly answers Doctrine's toSaveSql(). Pass true (the command's
 *   --force) to include them.
 */
final class SchemaDiffer
{
    /**
     * @param array<string,mixed> $from
     * @param array<string,mixed> $to
     * @return array{
     *   created: string[],
     *   dropped: string[],
     *   columnsAdded: array<string,string[]>,
     *   columnsRemoved: array<string,string[]>,
     *   columnsChanged: array<string,string[]>,
     *   empty: bool
     * }
     */
    public function diff(array $from, array $to, bool $allowDestructive = false): array
    {
        $created = array_values(array_diff(array_keys($to), array_keys($from)));
        $dropped = $allowDestructive
            ? array_values(array_diff(array_keys($from), array_keys($to)))
            : [];

        $columnsAdded   = [];
        $columnsRemoved = [];
        $columnsChanged = [];

        foreach (array_intersect(array_keys($from), array_keys($to)) as $table) {
            /** @var array<string,ColumnMeta> $fromCols */
            $fromCols = $from[$table]['columns'] ?? [];
            /** @var array<string,ColumnMeta> $toCols */
            $toCols = $to[$table]['columns'] ?? [];

            $added = array_values(array_diff(array_keys($toCols), array_keys($fromCols)));
            if ($added !== []) {
                $columnsAdded[$table] = $added;
            }

            if ($allowDestructive) {
                $removed = array_values(array_diff(array_keys($fromCols), array_keys($toCols)));
                if ($removed !== []) {
                    $columnsRemoved[$table] = $removed;
                }
            }

            $changed = [];
            foreach (array_intersect(array_keys($fromCols), array_keys($toCols)) as $col) {
                if (!$this->columnsEqual($fromCols[$col], $toCols[$col])) {
                    $changed[] = $col;
                }
            }
            if ($changed !== []) {
                $columnsChanged[$table] = $changed;
            }
        }

        $empty = $created === []
            && $dropped === []
            && $columnsAdded === []
            && $columnsRemoved === []
            && $columnsChanged === [];

        return [
            'created'        => $created,
            'dropped'        => $dropped,
            'columnsAdded'   => $columnsAdded,
            'columnsRemoved' => $columnsRemoved,
            'columnsChanged' => $columnsChanged,
            'empty'          => $empty,
        ];
    }

    /**
     * Render the diff as a single migration file source.
     *
     * @param array<string,mixed> $to   the target snapshot (for column metadata)
     * @param array<string,mixed> $diff result of diff()
     */
    public function render(array $diff, array $to, string $filename): string
    {
        if ($diff['empty']) {
            $body = "        // No schema differences detected.";
            $down = "        // Nothing to reverse.";
        } else {
            $body = implode("\n", $this->upLines($diff, $to));
            $down = implode("\n", $this->downLines($diff));
        }

        return <<<PHP
        <?php

        declare(strict_types=1);

        use AlfaCode\\LetMigrate\\Contract\\MigrationInterface;
        use AlfaCode\\LetMigrate\\Contract\\SchemaBuilderInterface;
        use AlfaCode\\LetMigrate\\Schema\\Blueprint;

        /**
         * Auto-generated by migrate:diff. Review before running.
         * Save-diff mode omits destructive DROPs unless generated with --force.
         */
        return new class implements MigrationInterface {
            public function up(SchemaBuilderInterface \$schema): void
            {
        {$body}
            }

            public function down(SchemaBuilderInterface \$schema): void
            {
        {$down}
            }
        };
        PHP;
    }

    // ── internals ─────────────────────────────────────────────────

    private function columnsEqual(ColumnMeta $a, ColumnMeta $b): bool
    {
        return strtolower($a->type) === strtolower($b->type)
            && $a->nullable === $b->nullable
            && (string) $a->default === (string) $b->default
            && $a->length === $b->length
            && $a->precision === $b->precision
            && $a->scale === $b->scale;
    }

    /**
     * @param array<string,mixed> $diff
     * @param array<string,mixed> $to
     * @return string[]
     */
    private function upLines(array $diff, array $to): array
    {
        $l = [];

        foreach ($diff['created'] as $table) {
            $l[] = "        \$schema->create('{$table}', function (Blueprint \$table) {";
            $l[] = "            // TODO: define columns for new table '{$table}'";
            $l[] = "            //       (run migrate:generate for a full table definition)";
            $l[] = "        });";
        }

        foreach ($diff['dropped'] as $table) {
            $l[] = "        \$schema->dropIfExists('{$table}'); // destructive (--force)";
        }

        $tables = array_unique(array_merge(
            array_keys($diff['columnsAdded']),
            array_keys($diff['columnsRemoved']),
            array_keys($diff['columnsChanged']),
        ));

        foreach ($tables as $table) {
            $l[] = "        \$schema->table('{$table}', function (Blueprint \$table) {";
            foreach ($diff['columnsAdded'][$table] ?? [] as $col) {
                $meta = $to[$table]['columns'][$col] ?? null;
                $type = $meta instanceof ColumnMeta ? strtoupper($meta->type) : 'VARCHAR(255)';
                $l[]  = "            \$table->addColumn('{$col}', '{$type}'); // review type";
            }
            foreach ($diff['columnsChanged'][$table] ?? [] as $col) {
                $meta = $to[$table]['columns'][$col] ?? null;
                $type = $meta instanceof ColumnMeta ? strtoupper($meta->type) : 'VARCHAR(255)';
                $l[]  = "            \$table->modifyColumn('{$col}', '{$type}'); // review";
            }
            foreach ($diff['columnsRemoved'][$table] ?? [] as $col) {
                $l[] = "            \$table->dropColumn('{$col}'); // destructive (--force)";
            }
            $l[] = "        });";
        }

        return $l;
    }

    /**
     * @param array<string,mixed> $diff
     * @return string[]
     */
    private function downLines(array $diff): array
    {
        $l = [];

        // Reverse created tables
        foreach ($diff['created'] as $table) {
            $l[] = "        \$schema->dropIfExists('{$table}');";
        }

        // Reverse added columns
        foreach ($diff['columnsAdded'] as $table => $cols) {
            $l[] = "        \$schema->table('{$table}', function (Blueprint \$table) {";
            foreach ($cols as $col) {
                $l[] = "            \$table->dropColumn('{$col}');";
            }
            $l[] = "        });";
        }

        if ($l === []) {
            $l[] = "        // Irreversible / destructive diff — no automatic down().";
        }

        return $l;
    }
}